DROP DATABASE IF EXISTS fitness_db;
CREATE DATABASE fitness_db;

USE fitness_db;

CREATE TABLE users (
  id INT  PRIMARY KEY AUTO_INCREMENT NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255) UNIQUE,
  password VARCHAR(255) UNIQUE NOT NULL
);